export type Lens = {
  id: number;
  name: string;
  brand: string;
  brandId: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  image: string;
  imageUrl?: string;
  color: "clear" | "colored";
  colorName?: string;
  usagePeriod: "daily" | "monthly" | "yearly";
  requiresPrescription: boolean;
  stock: number;
  badge?: string;
  description: string;
  dia: number;
  bc: number;
  sphRange: string;
  packSizes: number[];
  material: string;
  waterContent: number;
  oxygenPermeability: number;
  uvProtection: boolean;
  tags: string[];
  isToric?: boolean;
  cylOptions?: number[];   // örn: [-0.75, -1.25, -1.75, -2.25]
  axisOptions?: number[];  // örn: [10, 20, ..., 180]
};

export type Brand = {
  id: string;
  name: string;
  logo: string;
  bannerImage: string;
  bannerBg: string;
  tagline: string;
};

export type Review = {
  id: number;
  lensId: number;
  user: string;
  rating: number;
  date: string;
  comment: string;
  helpful: number;
  verified: boolean;
};

export const brands: Brand[] = [
  {
    id: "johnson",
    name: "Johnson & Johnson",
    logo: "👁️",
    bannerImage: "/brands/acuvue.jpg",
    bannerBg: "from-blue-900 to-blue-600",
    tagline: "Gün boyu konfor, kristal berraklığında görüş",
  },
  {
    id: "bausch",
    name: "Bausch + Lomb",
    logo: "🔬",
    bannerImage: "/brands/bausch.jpg",
    bannerBg: "from-green-900 to-emerald-600",
    tagline: "150 yıllık göz sağlığı uzmanlığı",
  },
  {
    id: "alcon",
    name: "Alcon (Ciba Vision)",
    logo: "🔵",
    bannerImage: "/brands/dailies.jpg",
    bannerBg: "from-cyan-800 to-cyan-500",
    tagline: "Her gün taze başlangıç",
  },
  {
    id: "cooper",
    name: "Cooper Vision",
    logo: "💙",
    bannerImage: "/brands/biofinity.jpg",
    bannerBg: "from-indigo-900 to-indigo-600",
    tagline: "Aylık konforun en üst noktası",
  },
  {
    id: "tech",
    name: "Tech Contactlens",
    logo: "✨",
    bannerImage: "/brands/freshlook.jpg",
    bannerBg: "from-purple-900 to-pink-600",
    tagline: "Yenilikçi lens teknolojileri",
  },
  {
    id: "zeiss",
    name: "Zeiss (Wöhlk)",
    logo: "🔭",
    bannerImage: "/brands/airoptix.jpg",
    bannerBg: "from-sky-800 to-teal-500",
    tagline: "Alman optik kalitesi",
  },
  {
    id: "acuvue",
    name: "Acuvue",
    logo: "👁️",
    bannerImage: "/brands/acuvue.jpg",
    bannerBg: "from-blue-900 to-blue-600",
    tagline: "Gün boyu konfor, kristal berraklığında görüş",
  },
  {
    id: "dailies",
    name: "Dailies",
    logo: "🔵",
    bannerImage: "/brands/dailies.jpg",
    bannerBg: "from-cyan-800 to-cyan-500",
    tagline: "Her gün taze başlangıç",
  },
  {
    id: "biofinity",
    name: "Biofinity",
    logo: "💙",
    bannerImage: "/brands/biofinity.jpg",
    bannerBg: "from-indigo-900 to-indigo-600",
    tagline: "Aylık konforun en üst noktası",
  },
  {
    id: "freshlook",
    name: "FreshLook",
    logo: "✨",
    bannerImage: "/brands/freshlook.jpg",
    bannerBg: "from-purple-900 to-pink-600",
    tagline: "Renkli dünyaya hoş geldiniz",
  },
  {
    id: "airoptix",
    name: "Air Optix",
    logo: "🌬️",
    bannerImage: "/brands/airoptix.jpg",
    bannerBg: "from-sky-800 to-teal-500",
    tagline: "Nefes alan teknoloji, özgür gözler",
  },
];

export const lenses: Lens[] = [
  // ACUVUE
  {
    id: 1,
    name: "Acuvue Oasys 1-Day",
    brand: "Acuvue",
    brandId: "acuvue",
    price: 349,
    originalPrice: 420,
    rating: 4.8,
    reviewCount: 1243,
    image: "/lenses/acuvue-oasys.jpg",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDAF8MM9gsCvBvcgjRL8YlI7FjlPCj9IV-UJyiDJ1jsEXi-bgVyWRXjNMKzM-_HH4eg8UpdGhGTIOLoOvePF3yPt4XKaYLc1sGQElyVzSyi-txSHTmotaFbqHzCNRnTm1nxlKQuZC6fhNLfb4-UWGIpGyV9d4vcsQ9Zd53cmsk_UzWShW2iu7Vdpr2JayOiqNS_QZ8YO8QBsz9b7V1q8fi__nxqCuGeqk-q70rZVOg6iMhGRnusxHFM8S_GoF92bhgS_SoXIBfEkEO3",
    color: "clear",
    usagePeriod: "daily",
    requiresPrescription: true,
    stock: 85,
    badge: "Çok Satan",
    description: "HydraLuxe teknolojisi ile göz yaşı benzeri nemlendirme. Ekran başında geçirilen uzun günler için ideal.",
    dia: 14.3,
    bc: 8.5,
    sphRange: "-12.00 / +8.00",
    packSizes: [30, 90],
    material: "Senofilcon A",
    waterContent: 38,
    oxygenPermeability: 121,
    uvProtection: true,
    tags: ["günlük", "şeffaf", "UV koruma", "ekran konforu"],
  },
  {
    id: 2,
    name: "Acuvue Moist",
    brand: "Acuvue",
    brandId: "acuvue",
    price: 219,
    originalPrice: 260,
    rating: 4.6,
    reviewCount: 876,
    image: "/lenses/acuvue-moist.jpg",
    color: "clear",
    usagePeriod: "daily",
    requiresPrescription: true,
    stock: 120,
    badge: "Kampanya",
    description: "LACREON teknolojisi ile gün boyu nemlendirme. Hafif ve neredeyse hissedilmez tasarım.",
    dia: 14.2,
    bc: 8.5,
    sphRange: "-12.00 / +6.00",
    packSizes: [30, 90],
    material: "Etafilcon A",
    waterContent: 58,
    oxygenPermeability: 28.9,
    uvProtection: true,
    tags: ["günlük", "şeffaf", "nemli", "başlangıç"],
  },
  {
    id: 3,
    name: "Acuvue Vita",
    brand: "Acuvue",
    brandId: "acuvue",
    price: 289,
    rating: 4.7,
    reviewCount: 542,
    image: "/lenses/acuvue-vita.jpg",
    color: "clear",
    usagePeriod: "monthly",
    requiresPrescription: true,
    stock: 60,
    description: "HydraMax teknolojisi ile aylık kullanımda sürdürülebilir nem. İlk günden son güne kadar konfor.",
    dia: 14.2,
    bc: 8.4,
    sphRange: "-12.00 / +6.00",
    packSizes: [6],
    material: "Senofilcon C",
    waterContent: 41,
    oxygenPermeability: 147,
    uvProtection: true,
    tags: ["aylık", "şeffaf", "yüksek oksijen"],
  },
  // DAILIES
  {
    id: 4,
    name: "Dailies Total1",
    brand: "Dailies",
    brandId: "dailies",
    price: 429,
    originalPrice: 499,
    rating: 4.9,
    reviewCount: 2108,
    image: "/lenses/dailies-total1.jpg",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBvTh0NZrEolnU6Lh5nA776iO57Nve14gidP9RxpAdahWjRRw3Uhl3dg35pONlQGLDEP-Www-hoJeobTyZUtpu74_GkDeGg-1FGYcLb6zdCuclv9ItbJi_yQxErOTKh2tLKYk2lTm9qtdDO8broVSbN5drP31IId82-n7RArR96oeRFd_OIEd911tI222Z88EIXwnq_vJLAYdjYZDG6WFmUjCgM1OANae49bqjbek0jTQ-l1AbEYwKC8E7QjN2mmYWFNIsw45Vp3dHI",
    color: "clear",
    usagePeriod: "daily",
    requiresPrescription: true,
    stock: 200,
    badge: "En Çok Satan",
    description: "Su gradyanı teknolojisi: merkez %33, yüzey %80 su içeriği. Lens takmadığınız hissi.",
    dia: 14.1,
    bc: 8.5,
    sphRange: "-12.00 / +6.00",
    packSizes: [30, 90],
    material: "Delefilcon A",
    waterContent: 80,
    oxygenPermeability: 156,
    uvProtection: false,
    tags: ["günlük", "şeffaf", "su gradyanı", "premium"],
  },
  {
    id: 5,
    name: "Dailies AquaComfort Plus",
    brand: "Dailies",
    brandId: "dailies",
    price: 198,
    rating: 4.5,
    reviewCount: 654,
    image: "/lenses/dailies-aqua.jpg",
    color: "clear",
    usagePeriod: "daily",
    requiresPrescription: true,
    stock: 150,
    description: "Göz kırpma aktivasyonlu nemlendirme sistemi. Her kırpışta taze nem.",
    dia: 14.0,
    bc: 8.7,
    sphRange: "-10.00 / +6.00",
    packSizes: [30, 90],
    material: "Nelfilcon A",
    waterContent: 69,
    oxygenPermeability: 26,
    uvProtection: false,
    tags: ["günlük", "şeffaf", "uygun fiyat"],
  },
  // BIOFINITY
  {
    id: 6,
    name: "Biofinity",
    brand: "Biofinity",
    brandId: "biofinity",
    price: 259,
    originalPrice: 299,
    rating: 4.7,
    reviewCount: 1876,
    image: "/lenses/biofinity.jpg",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDvramYMA9R3kxja5yIazlfjm4WuCIw7_LlwCds9CNpCMZWhQONyMpr58G4HTJ4aRk6-Gi2OGk31o2m-RONVf27UAz87F9sPbCP4t_P1Dzy3v5cktERbKLcrKU0ZZUaVRXKZKiGDXvVKrSuDA66gcJOfujaaUtTZeXyX5zPg6b9VthveVPbS0Td_CZ3AlO3OWcCbx0iE_6AQe6A2tHIJAUhkA2zO_tqRDhuOmcnana4_EcZ19zCbR2hxVYPympkwMQMOymq6JgGA0Aq",
    color: "clear",
    usagePeriod: "monthly",
    requiresPrescription: true,
    stock: 95,
    badge: "Popüler",
    description: "Aquaform teknolojisi ile silikon hidrojel. Doğal olarak nemli, oksijen geçirgenliği yüksek.",
    dia: 14.0,
    bc: 8.6,
    sphRange: "-12.00 / +8.00",
    packSizes: [6],
    material: "Comfilcon A",
    waterContent: 48,
    oxygenPermeability: 160,
    uvProtection: false,
    tags: ["aylık", "şeffaf", "silikon hidrojel", "yüksek Dk/t"],
  },
  {
    id: 7,
    name: "Biofinity Energys",
    brand: "Biofinity",
    brandId: "biofinity",
    price: 299,
    rating: 4.6,
    reviewCount: 432,
    image: "/lenses/biofinity-energys.jpg",
    color: "clear",
    usagePeriod: "monthly",
    requiresPrescription: true,
    stock: 70,
    description: "Digital Zone Optics teknolojisi ile dijital göz yorgunluğunu azaltır. Gün içi nem sirkülasyonu.",
    dia: 14.0,
    bc: 8.6,
    sphRange: "-12.00 / +6.00",
    packSizes: [6],
    material: "Comfilcon A",
    waterContent: 48,
    oxygenPermeability: 160,
    uvProtection: false,
    tags: ["aylık", "şeffaf", "dijital ekran", "enerji"],
  },
  // FRESHLOOK - Colored
  {
    id: 8,
    name: "FreshLook Colorblends - Mavi",
    brand: "FreshLook",
    brandId: "freshlook",
    price: 189,
    originalPrice: 229,
    rating: 4.5,
    reviewCount: 987,
    image: "/lenses/freshlook-blue.jpg",
    color: "colored",
    colorName: "Mavi",
    usagePeriod: "monthly",
    requiresPrescription: false,
    stock: 180,
    badge: "Trend",
    description: "3-renk teknolojisi ile doğal görünümlü mavi göz rengi. 0 numara versiyonu da mevcut.",
    dia: 14.5,
    bc: 8.6,
    sphRange: "-8.00 / +6.00",
    packSizes: [2, 6],
    material: "Phemfilcon A",
    waterContent: 55,
    oxygenPermeability: 19,
    uvProtection: false,
    tags: ["aylık", "renkli", "mavi", "estetik"],
  },
  {
    id: 9,
    name: "FreshLook Colorblends - Yeşil",
    brand: "FreshLook",
    brandId: "freshlook",
    price: 189,
    rating: 4.4,
    reviewCount: 765,
    image: "/lenses/freshlook-green.jpg",
    color: "colored",
    colorName: "Yeşil",
    usagePeriod: "monthly",
    requiresPrescription: false,
    stock: 140,
    description: "Doğal yeşil göz efekti. Koyu ve açık gözler için optimize edilmiş pigment derinliği.",
    dia: 14.5,
    bc: 8.6,
    sphRange: "-8.00 / +6.00",
    packSizes: [2, 6],
    material: "Phemfilcon A",
    waterContent: 55,
    oxygenPermeability: 19,
    uvProtection: false,
    tags: ["aylık", "renkli", "yeşil", "estetik"],
  },
  {
    id: 10,
    name: "FreshLook Colorblends - Kahverengi",
    brand: "FreshLook",
    brandId: "freshlook",
    price: 189,
    rating: 4.6,
    reviewCount: 1102,
    image: "/lenses/freshlook-brown.jpg",
    color: "colored",
    colorName: "Kahverengi",
    usagePeriod: "monthly",
    requiresPrescription: false,
    stock: 200,
    badge: "Çok Beğenilen",
    description: "Sıcak kahverengi tonu, Türkiye'de en çok tercih edilen renk. Güneş ışığında bal rengi efekti.",
    dia: 14.5,
    bc: 8.6,
    sphRange: "-8.00 / +6.00",
    packSizes: [2, 6],
    material: "Phemfilcon A",
    waterContent: 55,
    oxygenPermeability: 19,
    uvProtection: false,
    tags: ["aylık", "renkli", "kahverengi", "en çok tercih"],
  },
  // AIR OPTIX
  {
    id: 11,
    name: "Air Optix Plus HydraGlyde",
    brand: "Air Optix",
    brandId: "airoptix",
    price: 279,
    originalPrice: 319,
    rating: 4.7,
    reviewCount: 1456,
    image: "/lenses/airoptix-hydraglyde.jpg",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBzYX3SDGN-m3CLB0SSNHpDF4qqOS-U27-K67ZxNKD6xgF2cOOF_1hJ6mR-2iVVy8BxSwiClR7McsKW1OCsMHIx5Gaq3k1tTaqfRIPGATYO763bA_Ig7HEXcG9yo-CQ3lN7X4hW15AxgEIQ06AVTfR-1wSnwo9mFDJXesG2HHFJ5yDQ8qqZnwztqPzVZ0hYW1ylnn4DI-1e3dAxADv_MsIMSbb6a3-FfeFTM-oTRLcAhgEYq-mBWHuNg1fvR7VTZnhMvlzM6JYBAV18",
    color: "clear",
    usagePeriod: "monthly",
    requiresPrescription: true,
    stock: 110,
    badge: "Yeni",
    description: "SmartShield ve HydraGlyde teknolojileri birlikte. Protein birikimini engeller, nem kaybını önler.",
    dia: 14.2,
    bc: 8.6,
    sphRange: "-12.00 / +6.00",
    packSizes: [6],
    material: "Lotrafilcon B",
    waterContent: 33,
    oxygenPermeability: 138,
    uvProtection: false,
    tags: ["aylık", "şeffaf", "silikon hidrojel", "protein önleyici"],
  },
  {
    id: 12,
    name: "Air Optix Colors - Gri",
    brand: "Air Optix",
    brandId: "airoptix",
    price: 229,
    rating: 4.5,
    reviewCount: 634,
    image: "/lenses/airoptix-gray.jpg",
    color: "colored",
    colorName: "Gri",
    usagePeriod: "monthly",
    requiresPrescription: false,
    stock: 90,
    description: "Silikon hidrojel renkli lens. Yüksek oksijen geçirgenliği ile renkli lens konforunun zirvesi.",
    dia: 14.2,
    bc: 8.6,
    sphRange: "-8.00 / +6.00",
    packSizes: [2, 6],
    material: "Lotrafilcon B",
    waterContent: 33,
    oxygenPermeability: 138,
    uvProtection: false,
    tags: ["aylık", "renkli", "gri", "silikon hidrojel"],
  },
  // BAUSCH + LOMB
  {
    id: 13,
    name: "Biotrue ONEday",
    brand: "Bausch + Lomb",
    brandId: "bausch",
    price: 239,
    originalPrice: 279,
    rating: 4.6,
    reviewCount: 823,
    image: "/lenses/biotrue-oneday.jpg",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDyuJSNnQy3ZY5lU1_2hbcZM9mx1tf9BH3MxtWTDrjMX_atHkyO8B_oEd1vfA2cG-1ZESYw8SEQQs4BQMw87MEDEhbcZcRdhElNxkBrI9YsR5bq8o6fQ4Ua-nguASPF-x9xQukkKEBRnWsaoDQ7d-Qoa4AOd-JMjsWv4t9d1d1HwC5LsW9vwjJFuc11bnypUKhnglceS4unYzNxTRdxBARYBt3i9wUzrUVkIXczOyeEnY3h4uKQGgUD2KphvTC_GXRb9Ejp8MtUYAPN",
    color: "clear",
    usagePeriod: "daily",
    requiresPrescription: true,
    stock: 130,
    description: "Biyolojik ilham: göz yaşı benzeri %78 su içeriği. Hypergel materyal ile gün sonu konforu.",
    dia: 14.2,
    bc: 8.6,
    sphRange: "-12.00 / +6.00",
    packSizes: [30, 90],
    material: "Nesofilcon A",
    waterContent: 78,
    oxygenPermeability: 42,
    uvProtection: false,
    tags: ["günlük", "şeffaf", "yüksek nem", "biyouyumlu"],
  },
  {
    id: 14,
    name: "Ultra Monthly",
    brand: "Bausch + Lomb",
    brandId: "bausch",
    price: 319,
    rating: 4.8,
    reviewCount: 567,
    image: "/lenses/ultra-monthly.jpg",
    color: "clear",
    usagePeriod: "monthly",
    requiresPrescription: true,
    stock: 75,
    badge: "Premium",
    description: "MoistureSeal teknolojisi ile aylık boyunca %95 nem korunumu. Yüksek miyopi ve astigmat seçenekleri.",
    dia: 14.2,
    bc: 8.5,
    sphRange: "-12.00 / +6.00",
    packSizes: [6],
    material: "Samfilcon A",
    waterContent: 46,
    oxygenPermeability: 163,
    uvProtection: false,
    tags: ["aylık", "şeffaf", "premium", "astigmat uyumlu"],
    isToric: true,
    cylOptions: [-0.75, -1.25, -1.75, -2.25, -2.75],
    axisOptions: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180],
  },
  {
    id: 15,
    name: "SofLens Daily Disposable",
    brand: "Bausch + Lomb",
    brandId: "bausch",
    price: 169,
    rating: 4.3,
    reviewCount: 342,
    image: "/lenses/soflens-daily.jpg",
    color: "clear",
    usagePeriod: "daily",
    requiresPrescription: true,
    stock: 200,
    description: "Ekonomik günlük lens alternatifi. Uygun fiyatla kaliteli görüş kesmeksizin konfor.",
    dia: 14.2,
    bc: 8.6,
    sphRange: "-9.00 / +5.00",
    packSizes: [30, 90],
    material: "Hilafilcon B",
    waterContent: 59,
    oxygenPermeability: 22,
    uvProtection: false,
    tags: ["günlük", "şeffaf", "ekonomik", "başlangıç"],
  },
  {
    id: 16,
    name: "FreshLook One-Day - Mavi",
    brand: "FreshLook",
    brandId: "freshlook",
    price: 245,
    rating: 4.4,
    reviewCount: 289,
    image: "/lenses/freshlook-oneday-blue.jpg",
    color: "colored",
    colorName: "Mavi",
    usagePeriod: "daily",
    requiresPrescription: false,
    stock: 110,
    description: "Günlük renkli lens. Her gün temiz ve hijyenik kullanım. Solüsyon gerektirmez.",
    dia: 13.8,
    bc: 8.6,
    sphRange: "-6.00 / +6.00",
    packSizes: [10],
    material: "Etafilcon A",
    waterContent: 58,
    oxygenPermeability: 28.9,
    uvProtection: false,
    tags: ["günlük", "renkli", "mavi", "hijyenik"],
  },
  {
    id: 17,
    name: "Acuvue Define",
    brand: "Acuvue",
    brandId: "acuvue",
    price: 279,
    originalPrice: 329,
    rating: 4.7,
    reviewCount: 445,
    image: "/lenses/acuvue-define.jpg",
    color: "colored",
    colorName: "Doğal Parlak",
    usagePeriod: "monthly",
    requiresPrescription: false,
    stock: 85,
    badge: "Trend",
    description: "LACREON teknolojisi ile renkli lens. Gözü büyük ve parlak gösterir, iris desenini doğallaştırır.",
    dia: 14.2,
    bc: 8.5,
    sphRange: "-6.00 / +6.00",
    packSizes: [6],
    material: "Etafilcon A",
    waterContent: 58,
    oxygenPermeability: 28.9,
    uvProtection: false,
    tags: ["aylık", "renkli", "doğal", "büyük göz efekti"],
  },
  {
    id: 18,
    name: "Air Optix Night & Day",
    brand: "Air Optix",
    brandId: "airoptix",
    price: 389,
    rating: 4.5,
    reviewCount: 312,
    image: "/lenses/airoptix-nightday.jpg",
    color: "clear",
    usagePeriod: "monthly",
    requiresPrescription: true,
    stock: 45,
    badge: "Uzman Seçimi",
    description: "30 gece sürekli kullanım onaylı (göz doktoru kontrolünde). Dk/t=175 en yüksek oksijen geçirgenliği.",
    dia: 13.8,
    bc: 8.4,
    sphRange: "-10.00 / +6.00",
    packSizes: [6],
    material: "Lotrafilcon A",
    waterContent: 24,
    oxygenPermeability: 175,
    uvProtection: false,
    tags: ["aylık", "şeffaf", "gece kullanım", "maksimum oksijen"],
  },
  {
    id: 20,
    name: "Acuvue Oasys for Astigmatism",
    brand: "Acuvue",
    brandId: "acuvue",
    price: 389,
    originalPrice: 449,
    rating: 4.9,
    reviewCount: 812,
    image: "/lenses/acuvue-oasys-toric.jpg",
    imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=400&fit=crop&auto=format",
    color: "clear",
    usagePeriod: "monthly",
    requiresPrescription: true,
    stock: 95,
    badge: "Çok Satan",
    description: "HYDRACLEAR Plus teknolojisiyle astigmat için özel tasarlanmış aylık kontakt lens. Stabilite sistemi sayesinde lens, göz hareketlerine rağmen sabit kalır ve net görüş sağlar.",
    dia: 14.5,
    bc: 8.6,
    sphRange: "-9.00 / +4.00",
    packSizes: [6],
    material: "Senofilcon A",
    waterContent: 38,
    oxygenPermeability: 129,
    uvProtection: true,
    tags: ["aylık", "şeffaf", "astigmat", "toric", "astigmat uyumlu", "hidrasyon"],
    isToric: true,
    cylOptions: [-0.75, -1.25, -1.75, -2.25, -2.75],
    axisOptions: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180],
  },
];

export const reviews: Review[] = [
  { id: 1, lensId: 1, user: "Ayşe K.", rating: 5, date: "2026-04-12", comment: "Bütün gün bilgisayar başında çalışıyorum ve bu lenslerle gözlerim yorulmuyor. Kesinlikle tavsiye ederim!", helpful: 45, verified: true },
  { id: 2, lensId: 1, user: "Mehmet Y.", rating: 5, date: "2026-03-28", comment: "7 yıldır bu marka kullanıyorum, başka markaya geçemedim. Kalitesi tutarlı, hiç sorun yaşamadım.", helpful: 38, verified: true },
  { id: 3, lensId: 1, user: "Zeynep A.", rating: 4, date: "2026-02-15", comment: "Çok konforlu ama fiyatı biraz yüksek. Yine de değer.", helpful: 22, verified: true },
  { id: 4, lensId: 4, user: "Can Ö.", rating: 5, date: "2026-04-20", comment: "Lens taktığımı unutuyorum, gerçekten. Su gradyanı teknolojisi fark yaratıyor.", helpful: 67, verified: true },
  { id: 5, lensId: 4, user: "Fatma S.", rating: 5, date: "2026-04-01", comment: "Hafif kuruluktan şikayetçiydim, bunu denedim ve sorun tamamen geçti. Mucize gibi!", helpful: 54, verified: true },
  { id: 6, lensId: 8, user: "Selin K.", rating: 5, date: "2026-03-15", comment: "Rengi çok doğal görünüyor, herkes gözlerimin rengi sanıyor! Komşular 'ne zaman değiştin?' diye soruyor.", helpful: 89, verified: true },
  { id: 7, lensId: 8, user: "Burak T.", rating: 4, date: "2026-02-28", comment: "Güzel renk ama akşam biraz kuruyabiliyor. Damla ile hallettim.", helpful: 31, verified: false },
  { id: 8, lensId: 6, user: "Deniz M.", rating: 5, date: "2026-04-18", comment: "Aylık lens arayanlar için birebir. Kalitesi iyi, fiyatı makul.", helpful: 44, verified: true },
];

export const campaigns = [
  {
    id: 1,
    title: "Bahar Kampanyası",
    subtitle: "Günlük lenslerde %20 indirim",
    description: "Seçili Acuvue ve Dailies ürünlerinde geçerli",
    cta: "Hemen Keşfet",
    bg: "from-blue-600 via-blue-700 to-indigo-800",
    accent: "bg-yellow-400 text-yellow-900",
    emoji: "🌸",
  },
  {
    id: 2,
    title: "Renkli Lens Festivali",
    subtitle: "FreshLook ürünlerinde 2 al 1 öde",
    description: "Yaz moduna geç, renkli dünyayı keşfet",
    cta: "Ürünleri Gör",
    bg: "from-purple-600 via-pink-600 to-rose-500",
    accent: "bg-white text-purple-700",
    emoji: "✨",
  },
  {
    id: 3,
    title: "Premium Üyelik",
    subtitle: "HepsiLens Club'a katıl",
    description: "Her alışverişte puan kazan, özel indirimlerden yararlan",
    cta: "Ücretsiz Katıl",
    bg: "from-emerald-600 via-teal-600 to-cyan-700",
    accent: "bg-emerald-100 text-emerald-800",
    emoji: "💎",
  },
];

export const stripBrands = [
  { name: "Acuvue", emoji: "👁️", color: "text-blue-600" },
  { name: "Dailies", emoji: "🔵", color: "text-cyan-600" },
  { name: "Biofinity", emoji: "💙", color: "text-indigo-600" },
  { name: "FreshLook", emoji: "✨", color: "text-purple-600" },
  { name: "Air Optix", emoji: "🌬️", color: "text-sky-600" },
  { name: "Bausch+Lomb", emoji: "🔬", color: "text-green-600" },
  { name: "Acuvue", emoji: "👁️", color: "text-blue-600" },
  { name: "Dailies", emoji: "🔵", color: "text-cyan-600" },
];

export type Accessory = {
  id: number;
  name: string;
  brand: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  imageUrl?: string;
  description: string;
  badge?: string;
  brandId?: string;
  category: "solution" | "eyedrop";
};

export const accessories: Accessory[] = [
  { id: 101, name: "Renu MultiPlus", brand: "Bausch + Lomb", brandId: "bausch", price: 89, originalPrice: 110, rating: 4.7, reviewCount: 523, description: "Çok amaçlı lens bakım solüsyonu. Temizler, sterilize eder, depolar.", badge: "Çok Satan", category: "solution" },
  { id: 102, name: "Opti-Free Express", brand: "Alcon", brandId: "alcon", price: 95, rating: 4.6, reviewCount: 412, description: "Günlük ve aylık lensler için çok fonksiyonlu bakım solüsyonu.", category: "solution" },
  { id: 103, name: "Complete Easy Rub", brand: "AMO", brandId: "johnson", price: 72, originalPrice: 85, rating: 4.5, reviewCount: 289, description: "Kolay ovalama formülü ile hızlı lens temizliği.", category: "solution" },

  { id: 201, name: "Systane Ultra", brand: "Alcon", brandId: "alcon", price: 65, originalPrice: 79, rating: 4.8, reviewCount: 845, description: "Uzun süreli nem sağlayan göz damlası. Lens kullanıcıları için ideal.", badge: "En Çok Tercih", category: "eyedrop" },
  { id: 202, name: "Refresh Plus", brand: "Abbott", brandId: "johnson", price: 49, rating: 4.6, reviewCount: 612, description: "Koruyucu içermez, hassas gözler için uygundur.", category: "eyedrop" },
  { id: 203, name: "Hyabak", brand: "Thea", price: 85, originalPrice: 99, rating: 4.9, reviewCount: 387, badge: "Premium", description: "%0.15 sodyum hyaluronat. Yoğun kuru göz rahatlaması.", category: "eyedrop" },
];

export type Testimonial = {
  id: number;
  user: string;
  location: string;
  rating: number;
  comment: string;
  product: string;
  initials: string;
  color: string;
};

export const testimonials: Testimonial[] = [
  { id: 1, user: "Ayşe K.", location: "İstanbul", rating: 5, comment: "Bütün gün bilgisayar başında çalışıyorum ve bu lenslerle gözlerim yorulmuyor. Kesinlikle tavsiye ederim! Artık başka marka düşünemiyorum.", product: "Acuvue Oasys 1-Day", initials: "AK", color: "#003d9b" },
  { id: 2, user: "Mehmet Y.", location: "Ankara", rating: 5, comment: "7 yıldır bu marka kullanıyorum, başka markaya geçemedim. Kalitesi tutarlı, hiç sorun yaşamadım. Hepsilens üzerinden sipariş hızlı geldi.", product: "Acuvue Oasys 1-Day", initials: "MY", color: "#00687b" },
  { id: 3, user: "Can Ö.", location: "İzmir", rating: 5, comment: "Lens taktığımı unutuyorum, gerçekten. Su gradyanı teknolojisi fark yaratıyor. Sabah takıp akşam çıkarıyorum, hiç rahatsızlık yok.", product: "Dailies Total1", initials: "CÖ", color: "#6a3600" },
  { id: 4, user: "Fatma S.", location: "Bursa", rating: 5, comment: "Hafif kuruluktan şikayetçiydim, bunu denedim ve sorun tamamen geçti. Mucize gibi! Göz doktorum da bu lensi öneriyor.", product: "Dailies Total1", initials: "FS", color: "#003d9b" },
  { id: 5, user: "Selin K.", location: "İstanbul", rating: 5, comment: "Rengi çok doğal görünüyor, herkes gözlerimin rengi sanıyor! Arkadaşlarım 'ne zaman değiştin?' diye soruyor. Çok memnunum.", product: "FreshLook Colorblends - Mavi", initials: "SK", color: "#00687b" },
  { id: 6, user: "Deniz M.", location: "Antalya", rating: 5, comment: "Aylık lens arayanlar için birebir. Kalitesi iyi, fiyatı makul. Hepsilens'te hızlı kargo ile aynı gün elime geçti.", product: "Biofinity", initials: "DM", color: "#6a3600" },
  { id: 7, user: "Emre T.", location: "İstanbul", rating: 5, comment: "Astigmatım var ve Toric lensler hayatımı kolaylaştırdı. Artık gözlük takmak zorunda kalmıyorum. Hepsilens'i herkese öneririm.", product: "Air Optix Plus HydraGlyde", initials: "ET", color: "#003d9b" },
  { id: 8, user: "Nur A.", location: "Gaziantep", rating: 5, comment: "İlk kez lens kullandım ve bu kadar kolay olduğunu bilmiyordum. Hepsilens'in müşteri hizmetleri çok yardımcı oldu.", product: "Acuvue Moist", initials: "NA", color: "#00687b" },
];

export const faqItems = [
  { q: "Reçetesiz lens satın alabilir miyim?", a: "Renkli ve 0 numara lensler reçetesiz satın alınabilir. Numaralı şeffaf lensler için göz doktoru reçetesi gereklidir ve sipariş aşamasında reçetenizi yüklemeniz gerekmektedir." },
  { q: "Sipariş ne zaman gelir?", a: "İstanbul içi siparişler aynı gün veya ertesi iş günü, Türkiye geneli siparişler 1-3 iş günü içinde kargoya verilmektedir." },
  { q: "İade ve değişim şartları nedir?", a: "Açılmamış ve orijinal ambalajında ürünler 14 gün içinde iade edilebilir. Hijyen nedeniyle açılmış lens kutuları iade kabul edilmemektedir." },
  { q: "Lensi kaç saat takılı kalmalıyım?", a: "Günlük kullanım lensler maksimum 12-16 saat, aylık lensler ise uyku sırasında çıkarılmak üzere günlük 12-16 saat kullanılmalıdır. Doktorunuzun tavsiyelerine uymak önemlidir." },
  { q: "Hangi ödeme yöntemlerini kabul ediyorsunuz?", a: "Kredi kartı (3D Secure), banka kartı, havale/EFT, kapıda ödeme (nakit/kart) ve BNPL (şimdi al, sonra öde) seçenekleri mevcuttur." },
];
